[package]
name = "revvy02/tenet"
description = "Roblox networking library"
version = "0.0.5"
license = "MIT"
authors = ["revvy02"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"

exclude = ["**"]
include = ["src", "src/**", "wally.toml", "default.project.json", "LICENSE"]

[dependencies]
TestEZ = "roblox/testez@0.4.1"
Cleaner = "revvy02/cleaner@1.0.0"
Slick = "revvy02/slick@2.0.0"
TrueSignal = "revvy02/truesignal@1.0.2"
MockNetwork = "revvy02/mocknetwork@1.4.3"
Promise = "evaera/promise@4.0.0"
NetPass = "revvy02/netpass@0.1.3"
t = "osyrisrblx/t@3.0.0"